return {
	-- {
	-- 	"akinsho/bufferline.nvim",
	-- 	version = "*",
	-- 	dependencies = { "nvim-tree/nvim-web-devicons" },
	-- 	config = function()
	-- 		require("bufferline").setup({
	-- 			options = {
	-- 				mode = "buffers", -- show buffers, not real tabs
	-- 				diagnostics = "nvim_lsp",
	-- 				show_buffer_close_icons = false,
	-- 				show_close_icon = false,
	-- 				separator_style = "slant",
	-- 				always_show_bufferline = true,
	-- 				offsets = {
	-- 					{
	-- 						filetype = "NvimTree",
	-- 						text = "File Explorer",
	-- 						highlight = "Directory",
	-- 						text_align = "left",
	-- 					},
	-- 				},
	-- 			},
	-- 		})
	--
	-- 		-- Keymaps (VSCode-style tab switching)
	-- 		vim.keymap.set("n", "<C-[>", ":BufferLineCyclePrev<CR>", { desc = "Previous buffer" })
	-- 		vim.keymap.set("n", "<C-]>", ":BufferLineCycleNext<CR>", { desc = "Next buffer" })
	-- 		vim.keymap.set("n", "<leader>w", ":bdelete<CR>", { desc = "Close current buffer" })
	-- 	end,
	-- },
}
